# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/hk01-digital/hk01-ios-uikit-spec.git'

platform :ios, '9.0'

target 'DDMediatorDemo' do

  use_frameworks!
  pod 'DDKit/DDScan'
  pod 'DDKit/DDMediator'



end

target 'TestSDK' do
  use_frameworks!
  pod 'DDKit/DDScan'
  pod 'DDKit/DDMediator'

end
